### ISSUE TITLE
error in update method?

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/rails-api-library-demo#13] opened 2016-11-07 21:14 UTC
``` ruby
def update
  if @book.update(book_params)
    head :no_content
  else
    render json: @book.errors, status: :unprocessable_entity
  end
end
```

Doesn't having ```head :no_content``` destroy the record?

**Comment by raq929** [comment] 2016-11-11 22:28
No, it just sends and HTTP response with no headers.

**Comment by raq929** [comment] 2016-11-11 22:54
I tested update and it is working correctly.

**Comment by raq929** [comment] 2016-11-11 23:05
However, it is not returning something sensible. I'm updating to return the updated book.

**Comment by gaand** [comment] 2016-11-12 16:20
The API need not return updated book.  If the update worked, the client already knows the value of book.

**Comment by gaand** [comment] 2016-11-12 16:22
This issue should not be closed, but a merge will do that, so I'm not sure how our process should handle situations like this.

**Comment by raq929** [comment] 2016-11-12 16:23
As written, when I make a curl request, the book updates successfully, but
I get an 500 error. (Which is a bunch of mostly unreadable HTML).

**Comment by gaand** [comment] 2016-11-12 16:26
Then there is a different issue to address.

From `examples_controller.rb` in `rails-api-template`

```ruby
  def update
    if @example.update(example_params)
      head :no_content
    else
      render json: @example.errors, status: :unprocessable_entity
    end
  end
```

**Comment by raq929** [comment] 2016-11-12 16:32
That's what it looks like. (See Julie's original comment above.)

**Comment by gaand** [comment] 2016-11-12 16:33
Which works.

**Comment by gaand** [comment] 2016-11-12 16:35
You're saying it needs to change.  I'm saying it doesn't.  You'll need to provide more information for why you need to return data rather than fix the bug you seem to have.

**Comment by raq929** [comment] 2016-11-12 16:48
Long term, I agree with you. Short term, returning data fixes the bug, if not ideally. 

I confirmed that updating the example works on this repo. Which leaves me more confused about why updating a book gets an error. (Worse, is successful, but returns an error. Which leads me to believe the error is occurring AFTER the update runs. But there's nothing there that I can find.

**Comment by gaand** [comment] 2016-11-12 16:52
Okay, but the problem is your pull request will close this issue.

**Comment by raq929** [comment] 2016-11-12 16:55
Nevermind, I changed it back to 
```ruby
def update
  if @book.update(book_params)
    head :no_content
  else
    render json: @book.errors, status: :unprocessable_entity
  end
end
```

And it ran just fine. So.... no idea what was happening before. I will remove that commit and close the issue.

**Closed** 2016-11-12 17:00 UTC
